In [4]:
import numpy as np

# Given data
x1 = np.array([1, 2, 3])
x2 = np.array([2, 3, 4]) # Updated x2 values
y = np.array([1, 2, 3])

# Regularization parameter
lambda_val = 1

# --- Step 1: Construct the Design Matrix X ---
# Add a column of ones for the intercept (b0)
X = np.c_[np.ones(x1.shape[0]), x1, x2]
print("1. Design Matrix X:")
print(X)

# --- Step 2: Calculate (X^T X) ---
X_transpose_X = X.T @ X
print("\n2. (X^T X):")
print(X_transpose_X)

# --- Step 3: Create Identity Matrix I ---
# I must have the same dimension as X_transpose_X (3x3 in this case)
identity_matrix = np.identity(X.shape[1])
print("\n3. Identity Matrix I:")
print(identity_matrix)

# --- Step 4: Calculate (lambda * I) ---
lambda_I = lambda_val * identity_matrix
print("\n4. (lambda * I):")
print(lambda_I)

# --- Step 5: Calculate (X^T X + lambda * I) ---
term1 = X_transpose_X + lambda_I
print("\n5. (X^T X + lambda * I):")
print(term1)

# --- Step 6: Calculate the Inverse of term1 ---
inverse_term1 = np.linalg.inv(term1)
print("\n6. Inverse of (X^T X + lambda * I):")
print(inverse_term1)

# --- Step 7: Calculate (X^T y) ---
X_transpose_y = X.T @ y
print("\n7. (X^T y):")
print(X_transpose_y)

# --- Step 8: Calculate the Ridge Regression Coefficients (beta_ridge) ---
beta_ridge = inverse_term1 @ X_transpose_y

# Extract coefficients for b0, b1, b2
b0 = beta_ridge[0]
b1 = beta_ridge[1]
b2 = beta_ridge[2]

print(f"\n8. Ridge Regression Coefficients:")
print(f"b0 (intercept): {b0:.4f}")
print(f"b1: {b1:.4f}")
print(f"b2: {b2:.4f}")

print(f"\nTherefore, the model is approximately: y = {b0:.4f} + {b1:.4f}*x1 + {b2:.4f}*x2")

1. Design Matrix X:
[[1. 1. 2.]
 [1. 2. 3.]
 [1. 3. 4.]]

2. (X^T X):
[[ 3.  6.  9.]
 [ 6. 14. 20.]
 [ 9. 20. 29.]]

3. Identity Matrix I:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. (lambda * I):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

5. (X^T X + lambda * I):
[[ 4.  6.  9.]
 [ 6. 15. 20.]
 [ 9. 20. 30.]]

6. Inverse of (X^T X + lambda * I):
[[ 7.69230769e-01  5.92118946e-16 -2.30769231e-01]
 [ 7.68615940e-17  6.00000000e-01 -4.00000000e-01]
 [-2.30769231e-01 -4.00000000e-01  3.69230769e-01]]

7. (X^T y):
[ 6. 14. 20.]

8. Ridge Regression Coefficients:
b0 (intercept): 0.0000
b1: 0.4000
b2: 0.4000

Therefore, the model is approximately: y = 0.0000 + 0.4000*x1 + 0.4000*x2


In [6]:
import numpy as np

# Given data
x = np.array([2, 3, 4])
y = np.array([1, 2, 3])

# Regularization parameter
lambda_val = 1

# --- Step 1: Construct the Design Matrix X ---
# Add a column of ones for the intercept (b0)
X = np.c_[np.ones(x.shape[0]), x]
print("1. Design Matrix X:")
print(X)

# --- Step 2: Calculate (X^T X) ---
X_transpose_X = X.T @ X
print("\n2. (X^T X):")
print(X_transpose_X)

# --- Step 3: Create Identity Matrix I ---
# I must have the same dimension as X_transpose_X (2x2 in this case)
identity_matrix = np.identity(X.shape[1])
print("\n3. Identity Matrix I:")
print(identity_matrix)

# --- Step 4: Calculate (lambda * I) ---
lambda_I = lambda_val * identity_matrix
print("\n4. (lambda * I):")
print(lambda_I)

# --- Step 5: Calculate (X^T X + lambda * I) ---
term1 = X_transpose_X + lambda_I
print("\n5. (X^T X + lambda * I):")
print(term1)

# --- Step 6: Calculate the Inverse of term1 ---
inverse_term1 = np.linalg.inv(term1)
print("\n6. Inverse of (X^T X + lambda * I):")
print(inverse_term1)

# --- Step 7: Calculate (X^T y) ---
X_transpose_y = X.T @ y
print("\n7. (X^T y):")
print(X_transpose_y)

# --- Step 8: Calculate the Ridge Regression Coefficients (beta_ridge) ---
beta_ridge = inverse_term1 @ X_transpose_y

# Extract coefficients for b0, b1
b0 = beta_ridge[0]
b1 = beta_ridge[1]

print(f"\n8. Ridge Regression Coefficients:")
print(f"b0 (intercept): {b0:.4f}")
print(f"b1: {b1:.4f}")

print(f"\nTherefore, the model is approximately: y = {b0:.4f} + {b1:.4f}*x")

1. Design Matrix X:
[[1. 2.]
 [1. 3.]
 [1. 4.]]

2. (X^T X):
[[ 3.  9.]
 [ 9. 29.]]

3. Identity Matrix I:
[[1. 0.]
 [0. 1.]]

4. (lambda * I):
[[1. 0.]
 [0. 1.]]

5. (X^T X + lambda * I):
[[ 4.  9.]
 [ 9. 30.]]

6. Inverse of (X^T X + lambda * I):
[[ 0.76923077 -0.23076923]
 [-0.23076923  0.1025641 ]]

7. (X^T y):
[ 6. 20.]

8. Ridge Regression Coefficients:
b0 (intercept): -0.0000
b1: 0.6667

Therefore, the model is approximately: y = -0.0000 + 0.6667*x
